# Generated by Django 5.2.8 on 2025-12-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitemmodel_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
