# Generated by Django 5.2.8 on 2025-11-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='proudct_category',
            new_name='product_category',
        ),
    ]
