# Generated by Django 5.2.8 on 2025-11-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_proudct_category_productmodel_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_category',
            new_name='proudct_category',
        ),
    ]
