# Generated by Django 5.2.8 on 2025-12-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_couponmodel_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
