# Generated by Django 5.2.8 on 2025-12-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitemmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
