# Generated by Django 5.2.8 on 2026-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('ref_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
